#! /bin/sh

opwd=$PWD
tdir=`mktemp -d`
cd $tdir || exit 1
if test -d "$MY_DESKTOP_DATA_CHECKOUT"; then
    cp -aR "$MY_DESKTOP_DATA_CHECKOUT" desktop-data
    pushd desktop-data
    git checkout -f master
    git pull
    popd
else
    git clone git://gitorious.org/opensuse/desktop-data.git
fi
rm desktop-data/update_rpm
rm -rf desktop-data/.git
tar -cvj -f $opwd/desktop-data.tar.bz2 desktop-data
cd /
rm -rf $tdir
